version: 2

models:
  - name: dim_customers
    columns:
      - name: customer_key
        tests:
          - unique
          - not_null
      - name: email
        tests:
          - not_null

  - name: dim_products
    columns:
      - name: product_key
        tests:
          - unique
          - not_null
      - name: sku
        tests:
          - not_null

  - name: fact_orders
    columns:
      - name: order_key
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['Completed', 'Pending', 'Cancelled']
